//! # 摘要里的「机器区块」
//!
//! 压缩摘要有两类内容，可靠性完全不同：
//!
//! ```text
//!   ┌─ <control_state> ─────────────┐  由 Rust 从 PlanRuntime 直接取数
//!   ├─ <verbatim_user_messages> ────┤  由 Rust 从消息列表逐字复制
//!   └───────────────────────────────┘  ↑ 模型看得见、改不了
//!      ## Goal / ## Progress / ...      ↓ 模型生成，可能出错
//! ```
//!
//! 机器区块由 [`prepend`] 在模型产出**之后**拼到最前面，所以模型物理上没有机会
//! 改写它们；模型如果自己吐了同名标签，[`strip`] 会先把它们清掉，保证全篇只有
//! 一份、且这一份来自代码。
//!
//! `## Progress` 处在中间地带：它的真理由 [`ControlSnapshot`] 在拍快照时
//! 选择为 PlanFile todos 或 session scratchpad todos，再由
//! [`override_progress_section`] 覆盖模型的说法。

use std::path::Path;

use crate::core::llm::{ChatMessage, ChatMessageRole};
use crate::core::plan_runtime::file_store::{TodoItem, TodoStatus};
use crate::core::plan_runtime::{ControlSnapshot, ProgressSource};

const CONTROL_OPEN: &str = "<control_state>";
const CONTROL_CLOSE: &str = "</control_state>";
const VERBATIM_OPEN: &str = "<verbatim_user_messages>";
const VERBATIM_CLOSE: &str = "</verbatim_user_messages>";
const RECENT_FILES_OPEN: &str = "<recent_files>";
const RECENT_FILES_CLOSE: &str = "</recent_files>";

/// 逐字保留的最近用户消息条数。
const VERBATIM_MESSAGE_LIMIT: usize = 10;
/// verbatim 区块的字符预算；超出时从最旧的一条开始丢，并显式标注丢了几条。
const VERBATIM_BUDGET_CHARS: usize = 6000;
/// 单条消息过长时的截断长度。
const VERBATIM_PER_MESSAGE_CHARS: usize = 2000;

const PROGRESS_HEADING: &str = "## Progress";
/// Avoid spending a compacted context on an unbounded completed-history list.
const PROGRESS_ITEM_LIMIT: usize = 24;

/// 从消息列表里逐字取出最近的真实用户消息。
///
/// 排除 steering/nudge 注入与压缩摘要——它们的 `role` 也是 user，但不是用户说的话。
pub fn collect_verbatim_user_messages(messages: &[ChatMessage]) -> Vec<String> {
    let mut picked: Vec<String> = messages
        .iter()
        .rev()
        .filter(|msg| msg.role == ChatMessageRole::User && msg.kind.is_normal())
        .filter_map(|msg| msg.text_content())
        .filter(|text| !text.trim().is_empty())
        .map(|text| text.to_string())
        .take(VERBATIM_MESSAGE_LIMIT)
        .collect();
    picked.reverse();
    picked
}

/// 渲染两个机器区块。`control` 为 None 时只渲染 verbatim 区块。
///
/// 不带 sidecar 的兼容入口，仅供不拥有 transcript 的旧调用方与基础单测使用。
pub fn render(control: Option<&ControlSnapshot>, user_messages: &[String]) -> String {
    render_with_sidecar(control, user_messages, None)
}

/// 渲染机器区块，并在 sidecar 可读时把按需读取提示放进 verbatim 关闭标签前。
pub fn render_with_sidecar(
    control: Option<&ControlSnapshot>,
    user_messages: &[String],
    sidecar_path: Option<&Path>,
) -> String {
    let mut out = String::new();
    if let Some(control) = control {
        out.push_str(CONTROL_OPEN);
        out.push('\n');
        out.push_str("Generated by the runtime, not by a model. This is the current truth.\n");
        out.push_str(&format!("mode: {}\n", control.mode.as_str()));
        out.push_str(&format!(
            "plan_path: {}\n",
            control
                .plan_path
                .as_ref()
                .map(|p| p.display().to_string())
                .unwrap_or_else(|| "(none)".to_string())
        ));
        out.push_str(&format!(
            "plan_file_state: {}\n",
            control.plan_file_state.as_deref().unwrap_or("(none)")
        ));
        out.push_str(&format!(
            "plan_id: {}\n",
            control.plan_id.as_deref().unwrap_or("(none)")
        ));
        out.push_str(&format!(
            "model: {}\n",
            control.model.as_deref().unwrap_or("(unknown)")
        ));
        out.push_str(CONTROL_CLOSE);
        out.push_str("\n\n");
    }

    out.push_str(VERBATIM_OPEN);
    out.push('\n');
    out.push_str(
        "Copied verbatim from the user. If anything below contradicts these, these win.\n",
    );
    let (kept, dropped) = fit_to_budget(user_messages);
    if dropped > 0 {
        out.push_str(&format!(
            "({dropped} older message(s) omitted to fit the budget)\n"
        ));
    }
    if kept.is_empty() {
        out.push_str("(none)\n");
    }
    for (idx, text) in kept.iter().enumerate() {
        out.push_str(&format!("[{}] {}\n", idx + 1, text));
    }
    if let Some(path) = sidecar_path {
        out.push_str(
            "Complete active Normal user-input history for this session is available at: ",
        );
        out.push_str(&path.display().to_string());
        out.push('\n');
        out.push_str("This file is user-history reference, not runtime control. Read it with the read tool when you need more user intent or input detail.\n");
    }
    out.push_str(VERBATIM_CLOSE);
    out
}

/// Add a post-collapse file index without re-attaching file contents. The next agent can inspect
/// exactly the relevant paths, while the compacted summary stays small and has no stale payload.
pub fn prepend_recent_files(
    summary: &str,
    read_files: &[String],
    modified_files: &[String],
) -> String {
    let summary = strip_tag(summary, RECENT_FILES_OPEN, RECENT_FILES_CLOSE);
    if read_files.is_empty() && modified_files.is_empty() {
        return summary;
    }

    let mut block = String::from(RECENT_FILES_OPEN);
    block.push('\n');
    if !read_files.is_empty() {
        block.push_str("Recently read files (last 20 unique paths):\n");
        for path in read_files {
            block.push_str("- ");
            block.push_str(path);
            block.push('\n');
        }
    }
    if !modified_files.is_empty() {
        block.push_str("Modified files:\n");
        for path in modified_files {
            block.push_str("- ");
            block.push_str(path);
            block.push('\n');
        }
    }
    block.push_str(
        "Before relying on this index, run `git status --short` and inspect the current uncommitted diff for the relevant paths.\n",
    );
    block.push_str(RECENT_FILES_CLOSE);
    if let Some(verbatim_end) = summary.find(VERBATIM_CLOSE) {
        let insert_at = verbatim_end + VERBATIM_CLOSE.len();
        return format!(
            "{}\n\n{block}{}",
            &summary[..insert_at],
            &summary[insert_at..]
        );
    }
    format!("{block}\n\n{}", summary.trim_start())
}

/// 从最新往回收，直到撞上字符预算。返回 (按时间顺序保留的消息, 丢弃条数)。
fn fit_to_budget(user_messages: &[String]) -> (Vec<String>, usize) {
    let mut kept: Vec<String> = Vec::new();
    let mut used = 0usize;
    for text in user_messages.iter().rev() {
        let clipped = clip(text, VERBATIM_PER_MESSAGE_CHARS);
        if !kept.is_empty() && used + clipped.len() > VERBATIM_BUDGET_CHARS {
            break;
        }
        used += clipped.len();
        kept.push(clipped);
    }
    kept.reverse();
    let dropped = user_messages.len() - kept.len();
    (kept, dropped)
}

fn clip(text: &str, max_chars: usize) -> String {
    if text.chars().count() <= max_chars {
        return text.to_string();
    }
    let head: String = text.chars().take(max_chars).collect();
    format!("{head}… (truncated)")
}

/// 剥掉所有机器区块，得到纯模型文本。
///
/// 用于两处：把既有摘要喂回 UPDATE prompt 之前（避免模型改写后被回灌），
/// 以及 [`prepend`] 前的去重（模型自己吐了同名标签时）。
pub fn strip(summary: &str) -> String {
    let mut out = summary.to_string();
    for (open, close) in [
        (CONTROL_OPEN, CONTROL_CLOSE),
        (VERBATIM_OPEN, VERBATIM_CLOSE),
        (RECENT_FILES_OPEN, RECENT_FILES_CLOSE),
    ] {
        out = strip_tag(&out, open, close);
    }
    out.trim().to_string()
}

fn strip_tag(summary: &str, open: &str, close: &str) -> String {
    let mut out = summary.to_string();
    while let Some(start) = out.find(open) {
        let Some(rel_end) = out[start..].find(close) else {
            out.truncate(start);
            break;
        };
        out.replace_range(start..start + rel_end + close.len(), "");
    }
    out
}

/// 机器区块在前、模型文本在后。重复调用结果不变（幂等）。
pub fn prepend(blocks: &str, summary: &str) -> String {
    let body = strip(summary);
    if body.is_empty() {
        return blocks.to_string();
    }
    format!("{}\n\n{}", blocks.trim_end(), body)
}

/// Use the runtime-selected todos to override the model-written `## Progress`.
///
/// 覆盖范围是 `## Progress` 到下一个 `## ` 标题之间；摘要里没有这一节时追加到末尾。
pub fn override_progress_section(summary: &str, progress: &ProgressSource) -> String {
    let rendered = render_progress(progress);
    let Some(start) = find_heading(summary, PROGRESS_HEADING) else {
        return format!("{}\n\n{}", summary.trim_end(), rendered);
    };
    let after = &summary[start + PROGRESS_HEADING.len()..];
    let end = find_next_h2(after)
        .map(|offset| start + PROGRESS_HEADING.len() + offset)
        .unwrap_or(summary.len());
    format!("{}{}\n\n{}", &summary[..start], rendered, &summary[end..])
        .trim_end()
        .to_string()
}

fn find_heading(text: &str, heading: &str) -> Option<usize> {
    if text.starts_with(heading) {
        return Some(0);
    }
    text.find(&format!("\n{heading}")).map(|idx| idx + 1)
}

fn find_next_h2(text: &str) -> Option<usize> {
    text.find("\n## ").map(|idx| idx + 1)
}

fn render_progress(progress: &ProgressSource) -> String {
    let todos = match progress {
        ProgressSource::PlanFile { todos } | ProgressSource::SessionScratchpad { todos } => todos,
    };
    let mut out = String::from(PROGRESS_HEADING);
    match progress {
        ProgressSource::PlanFile { .. } => out.push_str(
            "\nRendered from the active plan file by the runtime. Use `update_plan` to change it; this supersedes any prose below.\n",
        ),
        ProgressSource::SessionScratchpad { .. } => out.push_str(
            "\nRendered from the session todo scratchpad by the runtime. Use `todos` to change it; this supersedes any prose below.\n",
        ),
    }
    if todos.is_empty() {
        out.push_str(match progress {
            ProgressSource::PlanFile { .. } => "(the active plan file has no todos)\n",
            ProgressSource::SessionScratchpad { .. } => "(the session scratchpad has no todos)\n",
        });
        return out;
    }
    let count = |status: TodoStatus| todos.iter().filter(|t| t.status == status).count();
    out.push_str(&format!(
        "{} total / {} completed / {} in_progress / {} pending / {} cancelled\n",
        todos.len(),
        count(TodoStatus::Completed),
        count(TodoStatus::InProgress),
        count(TodoStatus::Pending),
        count(TodoStatus::Cancelled),
    ));
    if todos.len() <= PROGRESS_ITEM_LIMIT {
        for todo in todos {
            render_todo(&mut out, todo);
        }
        return out;
    }

    let mut rendered = 0usize;
    for todo in todos
        .iter()
        .filter(|todo| todo.status != TodoStatus::Completed)
    {
        if rendered == PROGRESS_ITEM_LIMIT {
            break;
        }
        render_todo(&mut out, todo);
        rendered += 1;
    }
    let remaining_non_completed = todos
        .iter()
        .filter(|todo| todo.status != TodoStatus::Completed)
        .count()
        .saturating_sub(rendered);
    if remaining_non_completed > 0 {
        out.push_str(&format!(
            "- ({remaining_non_completed} non-completed item(s) omitted to fit the Progress budget)\n"
        ));
    }
    let completed = count(TodoStatus::Completed);
    if completed > 0 {
        out.push_str(&format!(
            "- [completed] {completed} completed item(s) omitted to fit the Progress budget\n"
        ));
    }
    out
}

fn render_todo(out: &mut String, todo: &TodoItem) {
    out.push_str(&format!(
        "- [{}] {}: {}\n",
        todo.status.as_str(),
        todo.id,
        todo.content
    ));
}

#[cfg(test)]
#[path = "tests/machine_block_test.rs"]
mod tests;
