import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { SessionBar } from "./SessionBar";
import { LocaleProvider } from "../i18n/LocaleProvider";
import { en } from "../../../src/shared/i18n/en";

afterEach(cleanup);
describe("SessionBar settings entry", () => {
  it("renders sibling icon actions, preserves selection and restores focus to the trigger", () => {
    const pin = vi.fn(); const remove = vi.fn(); const choose = vi.fn();
    const session = { sessionId: "s", title: "A session", updatedAt: Date.now(), busy: false, isCurrent: true, ownedByThisFrontend: true };
    render(<SessionBar activeSessionId="s" sessions={[session]} ready onOpenSettings={vi.fn()} onNewSession={vi.fn()} onSwitchSession={choose} onSetPinned={pin} onDeleteSession={remove} deleteSupported />);
    const trigger = screen.getByTestId("session-select");
    fireEvent.click(trigger);
    const row = screen.getByRole("listitem");
    expect(row.querySelectorAll("button")).toHaveLength(3);
    expect(row.querySelector("button button")).toBeNull();
    const pinButton = screen.getByRole("button", { name: en["session.pin"] });
    expect(pinButton.getAttribute("title")).toBe(en["session.pin"]);
    expect(pinButton.querySelector(".codicon-pin")).toBeTruthy();
    fireEvent.click(pinButton);
    expect(pin).toHaveBeenCalledWith("s", true);
    expect(choose).not.toHaveBeenCalled();
    expect(document.activeElement).toBe(trigger);
    fireEvent.click(trigger);
    const trash = screen.getByRole("button", { name: en["session.delete"] });
    expect(trash.querySelector(".codicon-trash")).toBeTruthy();
    fireEvent.click(trash);
    expect(remove).not.toHaveBeenCalled();
    const cancel = screen.getByTestId("delete-session-cancel");
    expect(document.activeElement).toBe(cancel);
    fireEvent.keyDown(cancel, { key: "Escape" });
    expect(remove).not.toHaveBeenCalled();
    expect(document.activeElement).toBe(trigger);
    fireEvent.click(trigger);
    fireEvent.click(screen.getByRole("button", { name: en["session.delete"] }));
    const confirm = screen.getByTestId("delete-session-delete");
    fireEvent.click(confirm);
    fireEvent.click(confirm);
    expect(remove).toHaveBeenCalledExactlyOnceWith("s");
    expect(document.activeElement).toBe(trigger);
  });
  it("offers unpin but explains why a busy session cannot be deleted", () => {
    const session = { sessionId: "s", title: "A", updatedAt: 1, busy: true, isPinned: true, isCurrent: true, ownedByThisFrontend: true };
    const view = render(<LocaleProvider locale="en"><SessionBar activeSessionId="s" sessions={[session]} ready onOpenSettings={vi.fn()} onNewSession={vi.fn()} onSwitchSession={vi.fn()} onSetPinned={vi.fn()} onDeleteSession={vi.fn()} deleteSupported /></LocaleProvider>);
    fireEvent.click(screen.getByTestId("session-select"));
    const pin = screen.getByRole("button", { name: en["session.unpin"] });
    expect(pin.querySelector(".codicon-pinned")).toBeTruthy();
    const trash = screen.getByRole("button", { name: en["session.delete"] }) as HTMLButtonElement;
    expect(trash.disabled).toBe(true);
    expect(trash.title).toBe(en["session.delete.busy"]);
    view.rerender(<LocaleProvider locale="zh-CN"><SessionBar activeSessionId="s" sessions={[session]} ready onOpenSettings={vi.fn()} onNewSession={vi.fn()} onSwitchSession={vi.fn()} onSetPinned={vi.fn()} onDeleteSession={vi.fn()} deleteSupported /></LocaleProvider>);
    expect(trash.isConnected).toBe(true);
    expect(trash.disabled).toBe(true);
    expect(pin.isConnected).toBe(true);
    expect(document.documentElement.lang).toBe("zh-CN");
  });
  it.each([{ ready: false, creating: false }, { ready: true, creating: true }])("keeps settings available independently of session readiness: %j", (props) => {
    const open = vi.fn();
    render(<LocaleProvider locale="en"><SessionBar {...props} activeSessionId={null} sessions={[]} onOpenSettings={open} onNewSession={vi.fn()} onSwitchSession={vi.fn()} /></LocaleProvider>);
    const button = screen.getByRole("button", { name: en["settings.title"] }) as HTMLButtonElement;
    expect(button.disabled).toBe(false);
    expect(button.title).toBe(en["settings.title"]);
    expect(button.querySelector(".codicon-settings-gear")).toBeTruthy();
    expect(screen.queryByTestId("compact-context-button")).toBeNull();
    fireEvent.click(button);
    expect(open).toHaveBeenCalledTimes(1);
  });
});
