// Generated by `tomcat serve --print-schema`.
// Do not edit by hand.

export type AssistantMessageEvent = any;

export interface GetMessagesParams {
  lastNTurns?: null | number;
  limit?: null | number;
}
export type Message = any;

export interface NewSessionParams {
  cwd?: null | string;
  mode?: ServeSessionMode | null;
}
export interface ServeAttachment {
  dataBase64?: null | string;
  fileId?: null | string;
  kind: ServeAttachmentKind;
  mimeType?: null | string;
}
export type ServeAttachmentKind = "image" | "file";

export interface ServeMessageParams {
  attachments?: ServeAttachment[];
}
export type ServeSessionMode = "code" | "claw";

export type ToolDisplay = {
  file: string;
  kind: "file";
} | {
  kind: "plan";
  plan: string;
} | {
  kind: "text";
  text: string;
};

export type ToolOutput = any;

export type ControlFrame = {
  payload?: any;
  requestId: string;
  sessionId?: null | string;
  subtype: string;
  type: "control_request";
} | {
  payload?: any;
  requestId: string;
  sessionId?: null | string;
  type: "control_cancel";
} | {
  payload?: any;
  requestId: string;
  sessionId?: null | string;
  type: "control_response";
};

export type OutFrame = ControlFrame | ResponseFrame | WireEvent;

export interface ResponseFrame {
  error?: null | string;
  id?: null | string;
  payload?: any;
  sessionId?: null | string;
  success: boolean;
  type: string;
}
export type ServeCommand = {
  id?: null | string;
  model: string;
  sessionId?: null | string;
  type: "set_model";
} | {
  id?: null | string;
  params?: GetMessagesParams;
  sessionId?: null | string;
  type: "get_messages";
} | {
  id?: null | string;
  params?: NewSessionParams;
  type: "new_session";
} | {
  id?: null | string;
  params?: ServeMessageParams;
  sessionId?: null | string;
  text: string;
  type: "follow_up";
} | {
  id?: null | string;
  params?: ServeMessageParams;
  sessionId?: null | string;
  text: string;
  type: "prompt";
} | {
  id?: null | string;
  params?: ServeMessageParams;
  sessionId?: null | string;
  text: string;
  type: "steer";
} | {
  id?: null | string;
  sessionId: string;
  type: "switch_session";
} | {
  id?: null | string;
  sessionId?: null | string;
  type: "close_session";
} | {
  id?: null | string;
  sessionId?: null | string;
  type: "get_state";
} | {
  id?: null | string;
  sessionId?: null | string;
  type: "interrupt";
} | {
  id?: null | string;
  type: "list_sessions";
} | {
  payload?: any;
  requestId: string;
  sessionId?: null | string;
  subtype: string;
  type: "control_request";
} | {
  payload?: any;
  requestId: string;
  sessionId?: null | string;
  type: "control_cancel";
} | {
  payload?: any;
  requestId: string;
  sessionId?: null | string;
  type: "control_response";
};

export type WireEvent = ({
  args: any;
  partialResult: ToolOutput;
  toolCallId: string;
  toolName: string;
  type: "tool_execution_update";
} | {
  args: any;
  toolCallId: string;
  toolName: string;
  type: "tool_execution_start";
} | {
  argsPreview: any;
  toolCallId: string;
  toolName: string;
  type: "tool_call_streaming";
} | {
  assistantMessageEvent: AssistantMessageEvent;
  message: Message;
  type: "message_update";
} | {
  attempt: number;
  delayMs: number;
  errorMessage: string;
  maxAttempts: number;
  type: "auto_retry_start";
} | {
  attempt: number;
  finalError?: null | string;
  success: boolean;
  type: "auto_retry_end";
} | {
  attempts: number;
  error: string;
  exhaustedAfterRetries: boolean;
  ratio?: null | number;
  source: string;
  type: "compaction_error";
} | {
  childSessionId: string;
  errorMessage?: null | string;
  outcome: string;
  parentSessionId: string;
  subagentType: string;
  type: "sub_agent_end";
} | {
  childSessionId: string;
  parentSessionId: string;
  spawnDepth: number;
  subagentType: string;
  type: "sub_agent_start";
} | {
  compactionCount: number;
  compactionTokensFreed: number;
  contextUtilizationRatio: number;
  inputTokensUsed: number;
  preheatInProgress: boolean;
  preheatResultPending: boolean;
  totalToolResultBytesPersisted: number;
  type: "context_metrics_update";
} | {
  coveredCount: number;
  elapsedMs: number;
  estimatedCoveredTokensBefore: number;
  estimatedSummaryTokens: number;
  estimatedTokensSaved: number;
  ratioAfter: number;
  summaryChars: number;
  type: "auto_compaction_end";
} | {
  coveredCount: number;
  estimatedTokensFreed: number;
  ratioAfter: number;
  ratioBefore: number;
  type: "boundary_switched";
  wasSyncWait: boolean;
} | {
  coveredCount: number;
  ratioBefore: number;
  type: "auto_compaction_start";
} | {
  display?: ToolDisplay | null;
  isError: boolean;
  result: ToolOutput;
  toolCallId: string;
  toolName: string;
  type: "tool_execution_end";
} | {
  error: string;
  event: string;
  extensionId?: null | string;
  type: "extension_error";
} | {
  error?: null | string;
  messages: Message[];
  type: "agent_end";
} | {
  errorCode?: null | string;
  errorMessage: string;
  reason: string;
  type: "llm_error";
} | {
  estimatedTokensFreed: number;
  ratioAfter: number;
  ratioBefore: number;
  turnsRemoved: number;
  type: "context_overflow_trim_end";
  willRetry: boolean;
} | {
  finishReason: string;
  message: string;
  type: "llm_notice";
} | {
  message: Message;
  toolResults: Message[];
  turnIndex: number;
  type: "turn_end";
} | {
  message: Message;
  type: "message_end";
} | {
  message: Message;
  type: "message_start";
} | {
  originalChars: number;
  persistedPath: string;
  toolName: string;
  type: "tool_result_persisted";
} | {
  originalChars: number;
  toolName: string;
  truncatedChars: number;
  type: "tool_result_truncated";
} | {
  partialTextLen: number;
  toolResultsCount: number;
  type: "agent_interrupted";
} | {
  persistTokensFreed: number;
  placeholderTokensFreed: number;
  type: "layer0_context_release";
} | {
  ratio: number;
  reason: string;
  type: "context_overflow_trim_start";
} | {
  timestamp: number;
  turnIndex: number;
  type: "turn_start";
} | {
  type: "agent_start";
}) & {
  sessionId?: null | string;
};

