use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use schemars::schema_for;
use serde::Serialize;
use serde_json::{Map, Value};

use crate::{resolve_agent_trail_dir, AppConfig, AppError};
use crate::infra::events::WireEvent;

use super::types::{ControlFrame, OutFrame, ResponseFrame, ServeCommand};

#[derive(Serialize)]
pub(crate) struct ServeSchemaBundle {
    serve_command: schemars::schema::RootSchema,
    control_frame: schemars::schema::RootSchema,
    response_frame: schemars::schema::RootSchema,
    wire_event: schemars::schema::RootSchema,
    out_frame: schemars::schema::RootSchema,
}

pub fn schema_output_dir(cfg: &AppConfig) -> Result<PathBuf, AppError> {
    if let Some(path) = cfg.serve.schema_out_dir.as_deref() {
        return crate::normalize_path(path);
    }
    Ok(resolve_agent_trail_dir(cfg)?.join("serve-schema"))
}

pub(crate) fn build_schema_bundle() -> ServeSchemaBundle {
    ServeSchemaBundle {
        serve_command: schema_for!(ServeCommand),
        control_frame: schema_for!(ControlFrame),
        response_frame: schema_for!(ResponseFrame),
        wire_event: schema_for!(WireEvent),
        out_frame: schema_for!(OutFrame),
    }
}

pub fn write_schema_bundle(cfg: &AppConfig) -> Result<PathBuf, AppError> {
    let out_dir = schema_output_dir(cfg)?;
    std::fs::create_dir_all(&out_dir).map_err(AppError::Io)?;
    let schema_path = out_dir.join("serve.schema.json");
    let dts_path = out_dir.join("serve.d.ts");
    std::fs::write(
        &schema_path,
        serde_json::to_vec_pretty(&build_schema_bundle())
            .map_err(|error| AppError::Config(format!("serialize serve schema failed: {error}")))?,
    )
    .map_err(AppError::Io)?;
    std::fs::write(&dts_path, serve_dts()).map_err(AppError::Io)?;
    Ok(out_dir)
}

pub fn serve_dts() -> String {
    render_typescript(&build_schema_bundle())
}

pub fn read_schema_fixture(path: &Path) -> Result<String, AppError> {
    std::fs::read_to_string(path).map_err(AppError::Io)
}

fn render_typescript(bundle: &ServeSchemaBundle) -> String {
    let root_schemas = [
        ("ServeCommand", &bundle.serve_command),
        ("ControlFrame", &bundle.control_frame),
        ("ResponseFrame", &bundle.response_frame),
        ("WireEvent", &bundle.wire_event),
        ("OutFrame", &bundle.out_frame),
    ];

    let root_names = root_schemas
        .iter()
        .map(|(name, _)| (*name).to_string())
        .collect::<BTreeSet<_>>();
    let mut definitions = BTreeMap::<String, Value>::new();
    let mut roots = BTreeMap::<String, Value>::new();

    for (name, schema) in root_schemas {
        let value =
            serde_json::to_value(schema).expect("serve schema bundle should serialize to json");
        collect_definitions(&value, &root_names, &mut definitions);
        roots.insert(name.to_string(), strip_root_metadata(value));
    }

    let mut out = String::from(
        "// Generated by `tomcat serve --print-schema`.\n// Do not edit by hand.\n\n",
    );
    for (name, schema) in &definitions {
        out.push_str(&emit_named_schema(name, schema));
        out.push('\n');
    }
    for (name, schema) in &roots {
        out.push_str(&emit_named_schema(name, schema));
        out.push('\n');
    }
    out
}

fn collect_definitions(
    root_value: &Value,
    root_names: &BTreeSet<String>,
    sink: &mut BTreeMap<String, Value>,
) {
    let Some(definitions) = root_value.get("definitions").and_then(Value::as_object) else {
        return;
    };
    for (name, schema) in definitions {
        if root_names.contains(name) || sink.contains_key(name) {
            continue;
        }
        sink.insert(name.clone(), strip_root_metadata(schema.clone()));
    }
}

fn strip_root_metadata(value: Value) -> Value {
    let Value::Object(mut object) = value else {
        return value;
    };
    object.remove("$schema");
    object.remove("title");
    object.remove("definitions");
    Value::Object(object)
}

fn emit_named_schema(name: &str, schema: &Value) -> String {
    if is_object_interface(schema) {
        format!(
            "export interface {name} {}",
            render_object_body(
                schema
                    .as_object()
                    .expect("object interface schema should be object"),
                0
            )
        )
    } else {
        format!("export type {name} = {};\n", render_type(schema, 0))
    }
}

fn is_object_interface(schema: &Value) -> bool {
    let Some(object) = schema.as_object() else {
        return false;
    };
    if object.contains_key("$ref")
        || object.contains_key("oneOf")
        || object.contains_key("anyOf")
        || object.contains_key("allOf")
        || object.contains_key("enum")
    {
        return false;
    }
    matches!(object.get("type"), Some(Value::String(kind)) if kind == "object")
        || object.contains_key("properties")
        || object.contains_key("additionalProperties")
}

fn render_type(schema: &Value, indent: usize) -> String {
    match schema {
        Value::Bool(true) => "any".to_string(),
        Value::Bool(false) => "never".to_string(),
        Value::Object(object) => {
            if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
                return reference_name(reference).to_string();
            }
            if let Some(variants) = object.get("enum").and_then(Value::as_array) {
                return variants
                    .iter()
                    .map(render_literal)
                    .collect::<Vec<_>>()
                    .join(" | ");
            }
            if let Some(variants) = object.get("oneOf").and_then(Value::as_array) {
                let rendered = render_union(variants, indent);
                return intersect_with_object_props(rendered, object, indent);
            }
            if let Some(variants) = object.get("anyOf").and_then(Value::as_array) {
                let rendered = render_union(variants, indent);
                return intersect_with_object_props(rendered, object, indent);
            }
            if let Some(variants) = object.get("allOf").and_then(Value::as_array) {
                let rendered = render_intersection(variants, indent);
                return intersect_with_object_props(rendered, object, indent);
            }
            if is_object_interface(schema) {
                return render_object_body(object, indent);
            }
            if let Some(kind) = object.get("type") {
                return render_type_keyword(kind, object, indent);
            }
            "any".to_string()
        }
        _ => "any".to_string(),
    }
}

fn render_union(variants: &[Value], indent: usize) -> String {
    let rendered = variants
        .iter()
        .map(|variant| render_type(variant, indent))
        .collect::<BTreeSet<_>>();
    rendered.into_iter().collect::<Vec<_>>().join(" | ")
}

fn render_intersection(variants: &[Value], indent: usize) -> String {
    let rendered = variants
        .iter()
        .map(|variant| render_type(variant, indent))
        .collect::<BTreeSet<_>>();
    rendered.into_iter().collect::<Vec<_>>().join(" & ")
}

fn intersect_with_object_props(rendered: String, object: &Map<String, Value>, indent: usize) -> String {
    if !has_object_props(object) {
        return rendered;
    }
    format!("({rendered}) & {}", render_object_body(object, indent))
}

fn render_type_keyword(kind: &Value, object: &Map<String, Value>, indent: usize) -> String {
    match kind {
        Value::String(kind) => match kind.as_str() {
            "string" => "string".to_string(),
            "integer" | "number" => "number".to_string(),
            "boolean" => "boolean".to_string(),
            "null" => "null".to_string(),
            "array" => {
                let item_type = object
                    .get("items")
                    .map(|items| render_type(items, indent + 1))
                    .unwrap_or_else(|| "any".to_string());
                format!("{item_type}[]")
            }
            "object" => render_object_body(object, indent),
            _ => "any".to_string(),
        },
        Value::Array(kinds) => {
            let rendered = kinds
                .iter()
                .map(|entry| render_type_keyword(entry, object, indent))
                .collect::<BTreeSet<_>>();
            rendered.into_iter().collect::<Vec<_>>().join(" | ")
        }
        _ => "any".to_string(),
    }
}

fn render_object_body(object: &Map<String, Value>, indent: usize) -> String {
    let props = object
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let required = object
        .get("required")
        .and_then(Value::as_array)
        .map(|values| {
            values
                .iter()
                .filter_map(Value::as_str)
                .map(ToOwned::to_owned)
                .collect::<BTreeSet<_>>()
        })
        .unwrap_or_default();
    let additional_properties = object.get("additionalProperties");

    if props.is_empty() {
        return match additional_properties {
            Some(Value::Bool(true)) | None => "Record<string, any>".to_string(),
            Some(Value::Bool(false)) => "{}".to_string(),
            Some(schema) => format!("Record<string, {}>", render_type(schema, indent + 1)),
        };
    }

    let mut lines = Vec::new();
    for (name, schema) in props {
        let optional = if required.contains(&name) { "" } else { "?" };
        lines.push(format!(
            "{}{}{}: {};",
            indent_str(indent + 1),
            property_name(&name),
            optional,
            render_type(&schema, indent + 1)
        ));
    }
    match additional_properties {
        Some(Value::Bool(true)) => lines.push(format!("{}[key: string]: any;", indent_str(indent + 1))),
        Some(Value::Bool(false)) | None => {}
        Some(schema) => lines.push(format!(
            "{}[key: string]: {};",
            indent_str(indent + 1),
            render_type(schema, indent + 1)
        )),
    }
    format!("{{\n{}\n{}}}", lines.join("\n"), indent_str(indent))
}

fn has_object_props(object: &Map<String, Value>) -> bool {
    object
        .get("properties")
        .and_then(Value::as_object)
        .map(|properties| !properties.is_empty())
        .unwrap_or(false)
        || object.contains_key("additionalProperties")
}

fn reference_name(reference: &str) -> &str {
    reference.rsplit('/').next().unwrap_or(reference)
}

fn render_literal(value: &Value) -> String {
    match value {
        Value::String(text) => format!("{text:?}"),
        Value::Number(number) => number.to_string(),
        Value::Bool(flag) => flag.to_string(),
        Value::Null => "null".to_string(),
        _ => "any".to_string(),
    }
}

fn property_name(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) if (first == '_' || first == '$' || first.is_ascii_alphabetic())
            && chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric()) =>
        {
            name.to_string()
        }
        _ => format!("{name:?}"),
    }
}

fn indent_str(indent: usize) -> String {
    "  ".repeat(indent)
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{build_schema_bundle, serve_dts};
    use crate::infra::events::{
        AgentEvent, AssistantMessageEvent, Message, ToolDisplay, ToolOutput, WireEvent,
    };

    #[test]
    fn serve_dts_emits_named_types_not_unknown() {
        let dts = serve_dts();
        assert!(dts.contains("export type ServeCommand = "));
        assert!(dts.contains("export type WireEvent = "));
        assert!(!dts.contains("export type ServeCommand = unknown;"));
        assert!(!dts.contains("export type OutFrame = unknown;"));
    }

    #[test]
    fn serve_dts_preserves_wire_event_session_id() {
        let dts = serve_dts();
        assert!(dts.contains("export type WireEvent = "));
        assert!(dts.contains("sessionId?: null | string;"));
    }

    #[test]
    fn build_schema_bundle_includes_wire_event() {
        let value = serde_json::to_value(build_schema_bundle()).expect("serialize schema bundle");
        assert!(value.get("wire_event").is_some(), "wire_event root missing");
    }

    #[test]
    fn serve_emitted_event_validates_against_generated_schema() {
        let bundle = build_schema_bundle();
        let schema = serde_json::to_value(&bundle.wire_event).expect("serialize wire event schema");
        let validator = jsonschema::validator_for(&schema).expect("compile wire event schema");
        let samples = vec![
            serde_json::to_value(WireEvent {
                session_id: Some("s1".to_string()),
                event: AgentEvent::MessageUpdate {
                    message: Message(json!({
                        "role": "assistant",
                        "content": "partial"
                    })),
                    assistant_message_event: AssistantMessageEvent(json!({
                        "kind": "content_delta",
                        "delta": "partial"
                    })),
                },
            })
            .expect("message_update sample"),
            serde_json::to_value(WireEvent {
                session_id: Some("s1".to_string()),
                event: AgentEvent::ToolExecutionStart {
                    tool_call_id: "call_1".to_string(),
                    tool_name: "ask_question".to_string(),
                    args: json!({"questions": [{"id": "q1"}]}),
                },
            })
            .expect("tool_execution_start sample"),
            serde_json::to_value(WireEvent {
                session_id: Some("s1".to_string()),
                event: AgentEvent::ToolExecutionEnd {
                    tool_call_id: "call_1".to_string(),
                    tool_name: "ask_question".to_string(),
                    result: ToolOutput(json!({"cancelled": true})),
                    display: Some(ToolDisplay::Text {
                        text: "cancelled".to_string(),
                    }),
                    is_error: false,
                },
            })
            .expect("tool_execution_end sample"),
            serde_json::to_value(WireEvent {
                session_id: Some("s1".to_string()),
                event: AgentEvent::AgentEnd {
                    messages: vec![Message(json!({
                        "role": "assistant",
                        "content": "done"
                    }))],
                    error: None,
                },
            })
            .expect("agent_end sample"),
        ];

        for sample in samples {
            assert!(
                validator.is_valid(&sample),
                "sample should validate against generated schema: {sample}"
            );
        }
    }
}
